[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles==23.2.1",
    "fastapi==0.109.0",
    "pillow==10.2.0",
    "pypdf2==3.0.1",
    "python-multipart==0.0.6",
    "uvicorn[standard]==0.27.0",
]
